<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>cppcheck</string>
    </array>
    <key>name</key>
    <string>Cppcheck</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>string.other</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>variable.other</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>constant.other</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(.+)\/(.+)\((.+)\):\s+(.+)</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text</string>
    <key>uuid</key>
    <string>fc54db6b-9aeb-48d1-b776-4d3d01ec325c</string>
</dict>
</plist>
